/*
 * THIS FILE WAS GENERATED BY C:\NET\WATT\UTIL\BCC_ERR.EXE. DO NOT EDIT.
 *
 * Watt-32 sys_errlist replaces vendor's sys_errlist
 */

#ifndef __BORLANDC__
#error This file is only for use by "__BORLANDC__"
#endif

char __syserr33[] = "Math argument (EDOM)";
char __syserr34[] = "Result too large (ERANGE)";
char __syserr20[] = "Arg list too big (E2BIG)";
char __syserr05[] = "Permission denied (EACCES)";
char __syserr42[] = "System error 42 (EAGAIN)";
char __syserr06[] = "Bad file number (EBADF)";
char __syserr44[] = "System error 44 (EBUSY)";
char __syserr24[] = "System error 24 (ECHILD)";
char __syserr48[] = "Resource deadlock avoided (EDEADLK)";
char __syserr35[] = "File already exists (EEXIST)";
char __syserr14[] = "System error 14 (EFAULT)";
char __syserr27[] = "System error 27 (EFBIG)";
char __syserr39[] = "System error 39 (EINTR)";
char __syserr19[] = "Invalid argument (EINVAL)";
char __syserr40[] = "System error 40 (EIO)";
char __syserr46[] = "System error 46 (EISDIR)";
char __syserr04[] = "Too many open files (EMFILE)";
char __syserr31[] = "System error 31 (EMLINK)";
char __syserr49[] = "File name too long (ENAMETOOLONG)";
char __syserr23[] = "System error 23 (ENFILE)";
char __syserr15[] = "No such device (ENODEV)";
char __syserr02[] = "No such file or directory (ENOENT)";
char __syserr21[] = "Exec format error (ENOEXEC)";
char __syserr50[] = "No locks available (ENOLCK)";
char __syserr08[] = "Not enough memory (ENOMEM)";
char __syserr28[] = "System error 28 (ENOSPC)";
char __syserr51[] = "Function not implemented (ENOSYS)";
char __syserr45[] = "System error 45 (ENOTDIR)";
char __syserr52[] = "Directory not empty (ENOTEMPTY)";
char __syserr25[] = "System error 25 (ENOTTY)";
char __syserr41[] = "System error 41 (ENXIO)";
char __syserr37[] = "System error 37 (EPERM)";
char __syserr32[] = "System error 32 (EPIPE)";
char __syserr30[] = "System error 30 (EROFS)";
char __syserr29[] = "System error 29 (ESPIPE)";
char __syserr38[] = "System error 38 (ESRCH)";
char __syserr22[] = "Cross-device link (EXDEV)";
char __syserr18[] = "No more files (ENMFILE)";
char __syserr53[] = "Too many levels of symbolic links (ELOOP)";
char __syserr54[] = "Value too large (EOVERFLOW)";
char __syserr55[] = "Multibyte/wide character encoding error (EILSEQ)";
char __syserr56[] = "Operation would block (EWOULDBLOCK)";
char __syserr57[] = "Operation now in progress (EINPROGRESS)";
char __syserr58[] = "Operation already in progress (EALREADY)";
char __syserr59[] = "Socket operation on non-socket (ENOTSOCK)";
char __syserr60[] = "Destination address required (EDESTADDRREQ)";
char __syserr61[] = "Message too long (EMSGSIZE)";
char __syserr62[] = "Protocol wrong type for socket (EPROTOTYPE)";
char __syserr63[] = "Protocol option not available (ENOPROTOOPT)";
char __syserr64[] = "Protocol not supported (EPROTONOSUPPORT)";
char __syserr65[] = "Socket type not supported (ESOCKTNOSUPPORT)";
char __syserr66[] = "Operation not supported on socket (EOPNOTSUPP)";
char __syserr67[] = "Protocol family not supported (EPFNOSUPPORT)";
char __syserr68[] = "Address family not supported by protocol (EAFNOSUPPORT)";
char __syserr69[] = "Address already in use (EADDRINUSE)";
char __syserr70[] = "Can't assign requested address (EADDRNOTAVAIL)";
char __syserr71[] = "Network is down (ENETDOWN)";
char __syserr72[] = "Network is unreachable (ENETUNREACH)";
char __syserr73[] = "Network dropped connection on reset (ENETRESET)";
char __syserr74[] = "Software caused connection abort (ECONNABORTED)";
char __syserr75[] = "Connection reset by peer (ECONNRESET)";
char __syserr76[] = "No buffer space available (ENOBUFS)";
char __syserr77[] = "Socket is already connected (EISCONN)";
char __syserr78[] = "Socket is not connected (ENOTCONN)";
char __syserr79[] = "Can't send after socket shutdown (ESHUTDOWN)";
char __syserr80[] = "Connection timed out (ETIMEDOUT)";
char __syserr81[] = "Connection refused (ECONNREFUSED)";
char __syserr82[] = "Host is down (EHOSTDOWN)";
char __syserr83[] = "No route to host (EHOSTUNREACH)";
char __syserr84[] = "Stale NFS file handle (ESTALE)";
char __syserr85[] = "Too many levels of remote in path (EREMOTE)";
char __syserr86[] = "RPC struct is bad (EBADRPC)";
char __syserr87[] = "RPC version wrong (ERPCMISMATCH)";
char __syserr88[] = "RPC prog. not avail (EPROGUNAVAIL)";
char __syserr89[] = "RPC Program version wrong (EPROGMISMATCH)";
char __syserr90[] = "Bad procedure for program (EPROCUNAVAIL)";
char __syserr01[] = "Invalid function number (EINVFNC)";
char __syserr03[] = "Path not found (ENOPATH)";
char __syserr07[] = "Memory arena trashed (ECONTR)";
char __syserr09[] = "Invalid memory block address (EINVMEM)";
char __syserr10[] = "Invalid environment (EINVENV)";
char __syserr11[] = "Invalid format (EINVFMT)";
char __syserr12[] = "Invalid access code (EINVACC)";
char __syserr13[] = "Invalid data (EINVDAT)";
char __syserr36[] = "Possible deadlock (EDEADLOCK)";
char __syserr16[] = "Attempted to remove current directory (ECURDIR)";
char __syserr17[] = "Not same device (ENOTSAM)";
char __syserr26[] = "System error 26 (ETXTBSY)";
char __syserr43[] = "System error 43 (ENOTBLK)";
char __syserr47[] = "System error 47 (EUCLEAN)";
char __syserr91[] = "Too many references (ETOOMANYREFS)";
char __syserr92[] = "Too many processes (EPROCLIM)";
char __syserr93[] = "Too many users (EUSERS)";
char __syserr94[] = "Disc quota exceeded (EDQUOT)";
char __syserr95[] = "RVD related disk error (EVDBAD)";
char __syserr96[] = "Out of remote working directory stuctures (ENORMTWD)";

char *SYS_ERRLIST[] = {
    __syserr00,  __syserr01,  __syserr02,  __syserr03,  __syserr04, 
    __syserr05,  __syserr06,  __syserr07,  __syserr08,  __syserr09, 
    __syserr10,  __syserr11,  __syserr12,  __syserr13,  __syserr14, 
    __syserr15,  __syserr16,  __syserr17,  __syserr18,  __syserr19, 
    __syserr20,  __syserr21,  __syserr22,  __syserr23,  __syserr24, 
    __syserr25,  __syserr26,  __syserr27,  __syserr28,  __syserr29, 
    __syserr30,  __syserr31,  __syserr32,  __syserr33,  __syserr34, 
    __syserr35,  __syserr36,  __syserr37,  __syserr38,  __syserr39, 
    __syserr40,  __syserr41,  __syserr42,  __syserr43,  __syserr44, 
    __syserr45,  __syserr46,  __syserr47,  __syserr48,  __syserr49, 
    __syserr50,  __syserr51,  __syserr52,  __syserr53,  __syserr54, 
    __syserr55,  __syserr56,  __syserr57,  __syserr58,  __syserr59, 
    __syserr60,  __syserr61,  __syserr62,  __syserr63,  __syserr64, 
    __syserr65,  __syserr66,  __syserr67,  __syserr68,  __syserr69, 
    __syserr70,  __syserr71,  __syserr72,  __syserr73,  __syserr74, 
    __syserr75,  __syserr76,  __syserr77,  __syserr78,  __syserr79, 
    __syserr80,  __syserr81,  __syserr82,  __syserr83,  __syserr84, 
    __syserr85,  __syserr86,  __syserr87,  __syserr88,  __syserr89, 
    __syserr90,  __syserr91,  __syserr92,  __syserr93,  __syserr94, 
    __syserr95,  __syserr96, 
};

